version: 2
updates:
  - package-ecosystem: cargo
    directory: "/backend"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/utils"
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directory: "/panel-frontend"
    schedule:
      interval: "daily"