[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.7"
toml_edit = "0.19"

argon2 = "0.5"
rand = "0.8.5"

log = "0.4"

tokio = { version = "1", features = ["full"] }
thiserror = "1"